apiVersion: v1
kind: Pod
metadata:
  name: javaapp
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /var/configuration
      name: log4j-volume
  volumes:
    - name: log4j-volume 
      configMap:
        name: log4j-config

# Run this command to create config map:
# kubectl create configmap log4j-config --from-file=log4j.xml

# To delete config map, run:
# kubectl delete configmap log4j-config 