apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: javaapp
  name: javaapp
spec:
  replicas: 1
  selector:
    matchLabels:
      run: javaapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: javaapp
      annotations:
        configmap.reloader.stakater.com/reload: "log4j-config"
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - mountPath: /var/configuration
          name: log4j-volume
    
      volumes:
      - name: log4j-volume 
        configMap:
          name: log4j-config

# Run this command to create config map:
# kubectl create configmap log4j-config --from-file=log4j.xml

# To delete config map, run:
# kubectl delete configmap log4j-config 