apiVersion: v1
kind: Pod
metadata:
  labels:
    app: guestbook
    tier: frontend
  name: kuard
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:1
    imagePullPolicy: IfNotPresent
    name: kuard
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
  dnsPolicy: ClusterFirst
  restartPolicy: Never
