apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: FOO_USER_NAME
        valueFrom:
          secretKeyRef:
              key: username
              name: dev-db-secret

      - name: FOO_PASS
        valueFrom:
          secretKeyRef:
              key: password
              name: dev-db-secret


# For Secret : kubectl create secret generic dev-db-secret --from-literal=username=devuser --from-literal=password='123456'
# See secret yaml : kubectl get secret dev-db-secret -o yaml

# For Deletion: kubectl delete secret dev-db-secret