apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      - name: top-secret
        mountPath: /var/configuration/
  volumes:
    - name: top-secret
      secret:
        secretName: user-pass

# For secret through file : kubectl create secret generic user-pass --from-file=userpass
# Check secret yaml :  

# kubectl delete secret user-pass