apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: nginx
  imagePullSecrets:
  - name: repository-secret

# From repo : kubectl create secret docker-registry repository-secret \
#    --docker-server=docker.io --docker-username=devengers \
#    --docker-password=123456 --docker-email=devengers@dev.com

# kubectl delete secret repository-secret