apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx

        volumeMounts:
        - name: tls
          mountPath: /usr/src/nginx/tls

      volumes:
      - name: tls
        secret:
          secretName: jenkins-tls-secret