apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx

        volumeMounts:
        - name: tls
          mountPath: /usr/src/nginx/tls

      volumes:
      - name: tls
        secret:
          secretName: jenkins-tls-secret

# Create tls secret : 
# openssl req -newkey rsa:2048 -nodes -keyout jenkins.key -x509 -days 365 -out jenkins.crt
# kubectl create secret tls jenkins-tls-secret --key=jenkins.key --cert=jenkins.crt

# kubectl delete secret jenkins-tls-secret